"""Report data models."""

from typing import List
from pydantic import BaseModel, Field
from datetime import datetime
from .analysis_result import AnalysisResult


class ReportSection(BaseModel):
    """A section in a report."""
    title: str
    content: str
    subsections: List['ReportSection'] = Field(default_factory=list)


class AnalyticalReport(BaseModel):
    """Detailed analytical report following data analyst standards."""
    title: str
    company_name: str
    generated_at: datetime = Field(default_factory=datetime.now)

    # Standard sections
    executive_summary: str
    methodology: str
    data_sources: List[str]
    analysis_results: List[AnalysisResult]

    # Main sections
    sections: List[ReportSection] = Field(default_factory=list)

    # Conclusion
    key_findings: List[str]
    limitations: List[str]

    def to_markdown(self) -> str:
        """Generate markdown formatted report."""
        md = f"""# {self.title}

**Company:** {self.company_name}
**Generated:** {self.generated_at.strftime('%Y-%m-%d %H:%M:%S')}

---

## Executive Summary

{self.executive_summary}

---

## Methodology

{self.methodology}

### Data Sources

{chr(10).join(f'- {ds}' for ds in self.data_sources)}

---

"""
        # Add sections
        for section in self.sections:
            md += self._section_to_markdown(section, level=2)

        # Key findings
        md += f"""
---

## Key Findings

{chr(10).join(f'{i+1}. {finding}' for i, finding in enumerate(self.key_findings))}

---

## Limitations

{chr(10).join(f'- {limitation}' for limitation in self.limitations)}

---

*Report generated by ETL to Insights AI Agent*
"""
        return md

    def _section_to_markdown(self, section: ReportSection, level: int) -> str:
        """Convert section to markdown recursively."""
        md = f"{'#' * level} {section.title}\n\n{section.content}\n\n"
        for subsection in section.subsections:
            md += self._section_to_markdown(subsection, level + 1)
        return md


class BusinessInsightReport(BaseModel):
    """Business-focused insight report."""
    title: str
    company_name: str
    generated_at: datetime = Field(default_factory=datetime.now)

    # Business sections
    executive_summary: str
    strategic_insights: List[str]
    challenges_addressed: List[str]
    opportunities_identified: List[str]
    action_items: List[str]
    expected_impact: str

    # Supporting data
    analysis_results: List[AnalysisResult]

    def to_markdown(self) -> str:
        """Generate markdown formatted business report."""
        return f"""# {self.title}

**Company:** {self.company_name}
**Generated:** {self.generated_at.strftime('%Y-%m-%d %H:%M:%S')}

---

## Executive Summary

{self.executive_summary}

---

## Strategic Insights

{chr(10).join(f'{i+1}. **{insight.split(".")[0]}**{insight[insight.find(".")+1:] if "." in insight else ""}' for i, insight in enumerate(self.strategic_insights))}

---

## Challenges Addressed

{chr(10).join(f'- {challenge}' for challenge in self.challenges_addressed)}

---

## Opportunities Identified

{chr(10).join(f'{i+1}. {opp}' for i, opp in enumerate(self.opportunities_identified))}

---

## Recommended Action Items

{chr(10).join(f'{i+1}. **Priority:** {action}' for i, action in enumerate(self.action_items))}

---

## Expected Impact

{self.expected_impact}

---

## Supporting Analysis

{len(self.analysis_results)} detailed analyses were conducted to support these insights.

{chr(10).join(f'- {result.challenge_title}' for result in self.analysis_results)}

---

*Report generated by ETL to Insights AI Agent*
"""
